/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class AAnnotationValueSpecListTail extends PAnnotationValueSpecListTail
{
    private TComma _comma_;
    private PAnnotationValueSpec _annotationValueSpec_;

    public AAnnotationValueSpecListTail()
    {
        // Constructor
    }

    public AAnnotationValueSpecListTail(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PAnnotationValueSpec _annotationValueSpec_)
    {
        // Constructor
        setComma(_comma_);

        setAnnotationValueSpec(_annotationValueSpec_);

    }

    @Override
    public Object clone()
    {
        return new AAnnotationValueSpecListTail(
            cloneNode(this._comma_),
            cloneNode(this._annotationValueSpec_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAnnotationValueSpecListTail(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PAnnotationValueSpec getAnnotationValueSpec()
    {
        return this._annotationValueSpec_;
    }

    public void setAnnotationValueSpec(PAnnotationValueSpec node)
    {
        if(this._annotationValueSpec_ != null)
        {
            this._annotationValueSpec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._annotationValueSpec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._annotationValueSpec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._annotationValueSpec_ == child)
        {
            this._annotationValueSpec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._annotationValueSpec_ == oldChild)
        {
            setAnnotationValueSpec((PAnnotationValueSpec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
