/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class AAssociationModifierList extends PAssociationModifierList
{
    private PAssociationModifier _associationModifier_;
    private PAssociationModifierList _associationModifierList_;

    public AAssociationModifierList()
    {
        // Constructor
    }

    public AAssociationModifierList(
        @SuppressWarnings("hiding") PAssociationModifier _associationModifier_,
        @SuppressWarnings("hiding") PAssociationModifierList _associationModifierList_)
    {
        // Constructor
        setAssociationModifier(_associationModifier_);

        setAssociationModifierList(_associationModifierList_);

    }

    @Override
    public Object clone()
    {
        return new AAssociationModifierList(
            cloneNode(this._associationModifier_),
            cloneNode(this._associationModifierList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssociationModifierList(this);
    }

    public PAssociationModifier getAssociationModifier()
    {
        return this._associationModifier_;
    }

    public void setAssociationModifier(PAssociationModifier node)
    {
        if(this._associationModifier_ != null)
        {
            this._associationModifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._associationModifier_ = node;
    }

    public PAssociationModifierList getAssociationModifierList()
    {
        return this._associationModifierList_;
    }

    public void setAssociationModifierList(PAssociationModifierList node)
    {
        if(this._associationModifierList_ != null)
        {
            this._associationModifierList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._associationModifierList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._associationModifier_)
            + toString(this._associationModifierList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._associationModifier_ == child)
        {
            this._associationModifier_ = null;
            return;
        }

        if(this._associationModifierList_ == child)
        {
            this._associationModifierList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._associationModifier_ == oldChild)
        {
            setAssociationModifier((PAssociationModifier) newChild);
            return;
        }

        if(this._associationModifierList_ == oldChild)
        {
            setAssociationModifierList((PAssociationModifierList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
