/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class ACast extends PCast
{
    private TAs _as_;
    private PSingleTypeIdentifier _singleTypeIdentifier_;

    public ACast()
    {
        // Constructor
    }

    public ACast(
        @SuppressWarnings("hiding") TAs _as_,
        @SuppressWarnings("hiding") PSingleTypeIdentifier _singleTypeIdentifier_)
    {
        // Constructor
        setAs(_as_);

        setSingleTypeIdentifier(_singleTypeIdentifier_);

    }

    @Override
    public Object clone()
    {
        return new ACast(
            cloneNode(this._as_),
            cloneNode(this._singleTypeIdentifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACast(this);
    }

    public TAs getAs()
    {
        return this._as_;
    }

    public void setAs(TAs node)
    {
        if(this._as_ != null)
        {
            this._as_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._as_ = node;
    }

    public PSingleTypeIdentifier getSingleTypeIdentifier()
    {
        return this._singleTypeIdentifier_;
    }

    public void setSingleTypeIdentifier(PSingleTypeIdentifier node)
    {
        if(this._singleTypeIdentifier_ != null)
        {
            this._singleTypeIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._singleTypeIdentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._as_)
            + toString(this._singleTypeIdentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._as_ == child)
        {
            this._as_ = null;
            return;
        }

        if(this._singleTypeIdentifier_ == child)
        {
            this._singleTypeIdentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._as_ == oldChild)
        {
            setAs((TAs) newChild);
            return;
        }

        if(this._singleTypeIdentifier_ == oldChild)
        {
            setSingleTypeIdentifier((PSingleTypeIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
