/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class AClassSpecializesItem extends PClassSpecializesItem
{
    private PAnnotations _annotations_;
    private PSingleTypeIdentifier _singleTypeIdentifier_;

    public AClassSpecializesItem()
    {
        // Constructor
    }

    public AClassSpecializesItem(
        @SuppressWarnings("hiding") PAnnotations _annotations_,
        @SuppressWarnings("hiding") PSingleTypeIdentifier _singleTypeIdentifier_)
    {
        // Constructor
        setAnnotations(_annotations_);

        setSingleTypeIdentifier(_singleTypeIdentifier_);

    }

    @Override
    public Object clone()
    {
        return new AClassSpecializesItem(
            cloneNode(this._annotations_),
            cloneNode(this._singleTypeIdentifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassSpecializesItem(this);
    }

    public PAnnotations getAnnotations()
    {
        return this._annotations_;
    }

    public void setAnnotations(PAnnotations node)
    {
        if(this._annotations_ != null)
        {
            this._annotations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._annotations_ = node;
    }

    public PSingleTypeIdentifier getSingleTypeIdentifier()
    {
        return this._singleTypeIdentifier_;
    }

    public void setSingleTypeIdentifier(PSingleTypeIdentifier node)
    {
        if(this._singleTypeIdentifier_ != null)
        {
            this._singleTypeIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._singleTypeIdentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._annotations_)
            + toString(this._singleTypeIdentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._annotations_ == child)
        {
            this._annotations_ = null;
            return;
        }

        if(this._singleTypeIdentifier_ == child)
        {
            this._singleTypeIdentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._annotations_ == oldChild)
        {
            setAnnotations((PAnnotations) newChild);
            return;
        }

        if(this._singleTypeIdentifier_ == oldChild)
        {
            setSingleTypeIdentifier((PSingleTypeIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
