/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class AComparisonBinaryOperator extends PBinaryOperator
{
    private PComparisonBinaryOperator _comparisonBinaryOperator_;

    public AComparisonBinaryOperator()
    {
        // Constructor
    }

    public AComparisonBinaryOperator(
        @SuppressWarnings("hiding") PComparisonBinaryOperator _comparisonBinaryOperator_)
    {
        // Constructor
        setComparisonBinaryOperator(_comparisonBinaryOperator_);

    }

    @Override
    public Object clone()
    {
        return new AComparisonBinaryOperator(
            cloneNode(this._comparisonBinaryOperator_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparisonBinaryOperator(this);
    }

    public PComparisonBinaryOperator getComparisonBinaryOperator()
    {
        return this._comparisonBinaryOperator_;
    }

    public void setComparisonBinaryOperator(PComparisonBinaryOperator node)
    {
        if(this._comparisonBinaryOperator_ != null)
        {
            this._comparisonBinaryOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparisonBinaryOperator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comparisonBinaryOperator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comparisonBinaryOperator_ == child)
        {
            this._comparisonBinaryOperator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comparisonBinaryOperator_ == oldChild)
        {
            setComparisonBinaryOperator((PComparisonBinaryOperator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
