/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import java.util.*;
import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class AGlobalDirectiveSection extends PGlobalDirectiveSection
{
    private final LinkedList<PGlobalDirective> _globalDirective_ = new LinkedList<PGlobalDirective>();

    public AGlobalDirectiveSection()
    {
        // Constructor
    }

    public AGlobalDirectiveSection(
        @SuppressWarnings("hiding") List<PGlobalDirective> _globalDirective_)
    {
        // Constructor
        setGlobalDirective(_globalDirective_);

    }

    @Override
    public Object clone()
    {
        return new AGlobalDirectiveSection(
            cloneList(this._globalDirective_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGlobalDirectiveSection(this);
    }

    public LinkedList<PGlobalDirective> getGlobalDirective()
    {
        return this._globalDirective_;
    }

    public void setGlobalDirective(List<PGlobalDirective> list)
    {
        this._globalDirective_.clear();
        this._globalDirective_.addAll(list);
        for(PGlobalDirective e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._globalDirective_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._globalDirective_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PGlobalDirective> i = this._globalDirective_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PGlobalDirective) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
