/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class ALoadGlobalDirective extends PGlobalDirective
{
    private PLoadDecl _loadDecl_;

    public ALoadGlobalDirective()
    {
        // Constructor
    }

    public ALoadGlobalDirective(
        @SuppressWarnings("hiding") PLoadDecl _loadDecl_)
    {
        // Constructor
        setLoadDecl(_loadDecl_);

    }

    @Override
    public Object clone()
    {
        return new ALoadGlobalDirective(
            cloneNode(this._loadDecl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALoadGlobalDirective(this);
    }

    public PLoadDecl getLoadDecl()
    {
        return this._loadDecl_;
    }

    public void setLoadDecl(PLoadDecl node)
    {
        if(this._loadDecl_ != null)
        {
            this._loadDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._loadDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._loadDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._loadDecl_ == child)
        {
            this._loadDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._loadDecl_ == oldChild)
        {
            setLoadDecl((PLoadDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
