/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplicityConstraintTail extends PMultiplicityConstraintTail
{
    private TComma _comma_;
    private PMultiplicityConstraint _multiplicityConstraint_;

    public AMultiplicityConstraintTail()
    {
        // Constructor
    }

    public AMultiplicityConstraintTail(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PMultiplicityConstraint _multiplicityConstraint_)
    {
        // Constructor
        setComma(_comma_);

        setMultiplicityConstraint(_multiplicityConstraint_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplicityConstraintTail(
            cloneNode(this._comma_),
            cloneNode(this._multiplicityConstraint_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplicityConstraintTail(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PMultiplicityConstraint getMultiplicityConstraint()
    {
        return this._multiplicityConstraint_;
    }

    public void setMultiplicityConstraint(PMultiplicityConstraint node)
    {
        if(this._multiplicityConstraint_ != null)
        {
            this._multiplicityConstraint_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiplicityConstraint_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._multiplicityConstraint_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._multiplicityConstraint_ == child)
        {
            this._multiplicityConstraint_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._multiplicityConstraint_ == oldChild)
        {
            setMultiplicityConstraint((PMultiplicityConstraint) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
