/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class AOwnedAssociationEnd extends PAssociationEnd
{
    private PAssociationOwnedEnd _associationOwnedEnd_;

    public AOwnedAssociationEnd()
    {
        // Constructor
    }

    public AOwnedAssociationEnd(
        @SuppressWarnings("hiding") PAssociationOwnedEnd _associationOwnedEnd_)
    {
        // Constructor
        setAssociationOwnedEnd(_associationOwnedEnd_);

    }

    @Override
    public Object clone()
    {
        return new AOwnedAssociationEnd(
            cloneNode(this._associationOwnedEnd_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOwnedAssociationEnd(this);
    }

    public PAssociationOwnedEnd getAssociationOwnedEnd()
    {
        return this._associationOwnedEnd_;
    }

    public void setAssociationOwnedEnd(PAssociationOwnedEnd node)
    {
        if(this._associationOwnedEnd_ != null)
        {
            this._associationOwnedEnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._associationOwnedEnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._associationOwnedEnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._associationOwnedEnd_ == child)
        {
            this._associationOwnedEnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._associationOwnedEnd_ == oldChild)
        {
            setAssociationOwnedEnd((PAssociationOwnedEnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
