/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class AParameterModifiers extends PParameterModifiers
{
    private PParameterModifierList _parameterModifierList_;

    public AParameterModifiers()
    {
        // Constructor
    }

    public AParameterModifiers(
        @SuppressWarnings("hiding") PParameterModifierList _parameterModifierList_)
    {
        // Constructor
        setParameterModifierList(_parameterModifierList_);

    }

    @Override
    public Object clone()
    {
        return new AParameterModifiers(
            cloneNode(this._parameterModifierList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParameterModifiers(this);
    }

    public PParameterModifierList getParameterModifierList()
    {
        return this._parameterModifierList_;
    }

    public void setParameterModifierList(PParameterModifierList node)
    {
        if(this._parameterModifierList_ != null)
        {
            this._parameterModifierList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parameterModifierList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parameterModifierList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parameterModifierList_ == child)
        {
            this._parameterModifierList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parameterModifierList_ == oldChild)
        {
            setParameterModifierList((PParameterModifierList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
