/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class ATerminateStateModifier extends PStateModifier
{
    private TTerminate _terminate_;

    public ATerminateStateModifier()
    {
        // Constructor
    }

    public ATerminateStateModifier(
        @SuppressWarnings("hiding") TTerminate _terminate_)
    {
        // Constructor
        setTerminate(_terminate_);

    }

    @Override
    public Object clone()
    {
        return new ATerminateStateModifier(
            cloneNode(this._terminate_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATerminateStateModifier(this);
    }

    public TTerminate getTerminate()
    {
        return this._terminate_;
    }

    public void setTerminate(TTerminate node)
    {
        if(this._terminate_ != null)
        {
            this._terminate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._terminate_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._terminate_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._terminate_ == child)
        {
            this._terminate_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._terminate_ == oldChild)
        {
            setTerminate((TTerminate) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
