/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

public abstract class PSingleTypeIdentifier extends Node
{
    // Empty body
}
