/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class TInout extends Token
{
    public TInout()
    {
        super.setText("inout");
    }

    public TInout(int line, int pos)
    {
        super.setText("inout");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInout(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInout(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInout text.");
    }
}
