/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class TOperation extends Token
{
    public TOperation()
    {
        super.setText("operation");
    }

    public TOperation(int line, int pos)
    {
        super.setText("operation");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOperation(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperation(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOperation text.");
    }
}
