/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class TProperty extends Token
{
    public TProperty()
    {
        super.setText("property");
    }

    public TProperty(int line, int pos)
    {
        super.setText("property");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProperty(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProperty(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProperty text.");
    }
}
