/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.internal.frontend.textuml.node;

import com.abstratt.mdd.internal.frontend.textuml.analysis.*;

@SuppressWarnings("nls")
public final class TRaises extends Token
{
    public TRaises()
    {
        super.setText("raises");
    }

    public TRaises(int line, int pos)
    {
        super.setText("raises");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRaises(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRaises(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRaises text.");
    }
}
