/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AClassImplementsListTail extends PClassImplementsListTail
{
    private TComma _comma_;
    private PClassImplementsItem _classImplementsItem_;

    public AClassImplementsListTail()
    {
        // Constructor
    }

    public AClassImplementsListTail(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PClassImplementsItem _classImplementsItem_)
    {
        // Constructor
        setComma(_comma_);

        setClassImplementsItem(_classImplementsItem_);

    }

    @Override
    public Object clone()
    {
        return new AClassImplementsListTail(
            cloneNode(this._comma_),
            cloneNode(this._classImplementsItem_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassImplementsListTail(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PClassImplementsItem getClassImplementsItem()
    {
        return this._classImplementsItem_;
    }

    public void setClassImplementsItem(PClassImplementsItem node)
    {
        if(this._classImplementsItem_ != null)
        {
            this._classImplementsItem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classImplementsItem_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._classImplementsItem_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._classImplementsItem_ == child)
        {
            this._classImplementsItem_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._classImplementsItem_ == oldChild)
        {
            setClassImplementsItem((PClassImplementsItem) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
