/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ANamedSimpleValueAdditional extends PNamedSimpleValueAdditional
{
    private TComma _comma_;
    private PNamedSimpleValue _namedSimpleValue_;

    public ANamedSimpleValueAdditional()
    {
        // Constructor
    }

    public ANamedSimpleValueAdditional(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PNamedSimpleValue _namedSimpleValue_)
    {
        // Constructor
        setComma(_comma_);

        setNamedSimpleValue(_namedSimpleValue_);

    }

    @Override
    public Object clone()
    {
        return new ANamedSimpleValueAdditional(
            cloneNode(this._comma_),
            cloneNode(this._namedSimpleValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANamedSimpleValueAdditional(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PNamedSimpleValue getNamedSimpleValue()
    {
        return this._namedSimpleValue_;
    }

    public void setNamedSimpleValue(PNamedSimpleValue node)
    {
        if(this._namedSimpleValue_ != null)
        {
            this._namedSimpleValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._namedSimpleValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._namedSimpleValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._namedSimpleValue_ == child)
        {
            this._namedSimpleValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._namedSimpleValue_ == oldChild)
        {
            setNamedSimpleValue((PNamedSimpleValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
