/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

public abstract class PWildcardTypeTail extends Node
{
    // Empty body
}
