/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AAllAccessCapabilities extends PAccessCapabilities
{
    private TAll _all_;

    public AAllAccessCapabilities()
    {
        // Constructor
    }

    public AAllAccessCapabilities(
        @SuppressWarnings("hiding") TAll _all_)
    {
        // Constructor
        setAll(_all_);

    }

    @Override
    public Object clone()
    {
        return new AAllAccessCapabilities(
            cloneNode(this._all_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAllAccessCapabilities(this);
    }

    public TAll getAll()
    {
        return this._all_;
    }

    public void setAll(TAll node)
    {
        if(this._all_ != null)
        {
            this._all_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._all_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._all_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._all_ == child)
        {
            this._all_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._all_ == oldChild)
        {
            setAll((TAll) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
