/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AAlt0ExpressionP0 extends PExpressionP0
{
    private POperand _operand_;

    public AAlt0ExpressionP0()
    {
        // Constructor
    }

    public AAlt0ExpressionP0(
        @SuppressWarnings("hiding") POperand _operand_)
    {
        // Constructor
        setOperand(_operand_);

    }

    @Override
    public Object clone()
    {
        return new AAlt0ExpressionP0(
            cloneNode(this._operand_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAlt0ExpressionP0(this);
    }

    public POperand getOperand()
    {
        return this._operand_;
    }

    public void setOperand(POperand node)
    {
        if(this._operand_ != null)
        {
            this._operand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._operand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._operand_ == child)
        {
            this._operand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._operand_ == oldChild)
        {
            setOperand((POperand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
