/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AAssociationAssociationKind extends PAssociationKind
{
    private TAssociation _association_;

    public AAssociationAssociationKind()
    {
        // Constructor
    }

    public AAssociationAssociationKind(
        @SuppressWarnings("hiding") TAssociation _association_)
    {
        // Constructor
        setAssociation(_association_);

    }

    @Override
    public Object clone()
    {
        return new AAssociationAssociationKind(
            cloneNode(this._association_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssociationAssociationKind(this);
    }

    public TAssociation getAssociation()
    {
        return this._association_;
    }

    public void setAssociation(TAssociation node)
    {
        if(this._association_ != null)
        {
            this._association_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._association_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._association_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._association_ == child)
        {
            this._association_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._association_ == oldChild)
        {
            setAssociation((TAssociation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
