/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AClosureExpressionP1 extends PExpressionP1
{
    private PClosure _closure_;

    public AClosureExpressionP1()
    {
        // Constructor
    }

    public AClosureExpressionP1(
        @SuppressWarnings("hiding") PClosure _closure_)
    {
        // Constructor
        setClosure(_closure_);

    }

    @Override
    public Object clone()
    {
        return new AClosureExpressionP1(
            cloneNode(this._closure_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClosureExpressionP1(this);
    }

    public PClosure getClosure()
    {
        return this._closure_;
    }

    public void setClosure(PClosure node)
    {
        if(this._closure_ != null)
        {
            this._closure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closure_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._closure_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._closure_ == child)
        {
            this._closure_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._closure_ == oldChild)
        {
            setClosure((PClosure) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
