/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AConstructorOperationKeyword extends POperationKeyword
{
    private TConstructor _constructor_;

    public AConstructorOperationKeyword()
    {
        // Constructor
    }

    public AConstructorOperationKeyword(
        @SuppressWarnings("hiding") TConstructor _constructor_)
    {
        // Constructor
        setConstructor(_constructor_);

    }

    @Override
    public Object clone()
    {
        return new AConstructorOperationKeyword(
            cloneNode(this._constructor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstructorOperationKeyword(this);
    }

    public TConstructor getConstructor()
    {
        return this._constructor_;
    }

    public void setConstructor(TConstructor node)
    {
        if(this._constructor_ != null)
        {
            this._constructor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constructor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constructor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constructor_ == child)
        {
            this._constructor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._constructor_ == oldChild)
        {
            setConstructor((TConstructor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
