/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AExtentIdentifierExpression extends PIdentifierExpression
{
    private PMinimalTypeIdentifier _minimalTypeIdentifier_;
    private TExtent _extent_;

    public AExtentIdentifierExpression()
    {
        // Constructor
    }

    public AExtentIdentifierExpression(
        @SuppressWarnings("hiding") PMinimalTypeIdentifier _minimalTypeIdentifier_,
        @SuppressWarnings("hiding") TExtent _extent_)
    {
        // Constructor
        setMinimalTypeIdentifier(_minimalTypeIdentifier_);

        setExtent(_extent_);

    }

    @Override
    public Object clone()
    {
        return new AExtentIdentifierExpression(
            cloneNode(this._minimalTypeIdentifier_),
            cloneNode(this._extent_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExtentIdentifierExpression(this);
    }

    public PMinimalTypeIdentifier getMinimalTypeIdentifier()
    {
        return this._minimalTypeIdentifier_;
    }

    public void setMinimalTypeIdentifier(PMinimalTypeIdentifier node)
    {
        if(this._minimalTypeIdentifier_ != null)
        {
            this._minimalTypeIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minimalTypeIdentifier_ = node;
    }

    public TExtent getExtent()
    {
        return this._extent_;
    }

    public void setExtent(TExtent node)
    {
        if(this._extent_ != null)
        {
            this._extent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._extent_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minimalTypeIdentifier_)
            + toString(this._extent_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minimalTypeIdentifier_ == child)
        {
            this._minimalTypeIdentifier_ = null;
            return;
        }

        if(this._extent_ == child)
        {
            this._extent_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minimalTypeIdentifier_ == oldChild)
        {
            setMinimalTypeIdentifier((PMinimalTypeIdentifier) newChild);
            return;
        }

        if(this._extent_ == oldChild)
        {
            setExtent((TExtent) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
