/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AInvariantFeatureType extends PFeatureType
{
    private PInvariantDecl _invariantDecl_;

    public AInvariantFeatureType()
    {
        // Constructor
    }

    public AInvariantFeatureType(
        @SuppressWarnings("hiding") PInvariantDecl _invariantDecl_)
    {
        // Constructor
        setInvariantDecl(_invariantDecl_);

    }

    @Override
    public Object clone()
    {
        return new AInvariantFeatureType(
            cloneNode(this._invariantDecl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInvariantFeatureType(this);
    }

    public PInvariantDecl getInvariantDecl()
    {
        return this._invariantDecl_;
    }

    public void setInvariantDecl(PInvariantDecl node)
    {
        if(this._invariantDecl_ != null)
        {
            this._invariantDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._invariantDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._invariantDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._invariantDecl_ == child)
        {
            this._invariantDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._invariantDecl_ == oldChild)
        {
            setInvariantDecl((PInvariantDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
