/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AInvariantFeatureType extends PFeatureType
{
    private PClassInvariantDecl _classInvariantDecl_;

    public AInvariantFeatureType()
    {
        // Constructor
    }

    public AInvariantFeatureType(
        @SuppressWarnings("hiding") PClassInvariantDecl _classInvariantDecl_)
    {
        // Constructor
        setClassInvariantDecl(_classInvariantDecl_);

    }

    @Override
    public Object clone()
    {
        return new AInvariantFeatureType(
            cloneNode(this._classInvariantDecl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInvariantFeatureType(this);
    }

    public PClassInvariantDecl getClassInvariantDecl()
    {
        return this._classInvariantDecl_;
    }

    public void setClassInvariantDecl(PClassInvariantDecl node)
    {
        if(this._classInvariantDecl_ != null)
        {
            this._classInvariantDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classInvariantDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classInvariantDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classInvariantDecl_ == child)
        {
            this._classInvariantDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classInvariantDecl_ == oldChild)
        {
            setClassInvariantDecl((PClassInvariantDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
