/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ALiteralFeatureType extends PFeatureType
{
    private PEnumerationLiteralDecl _enumerationLiteralDecl_;

    public ALiteralFeatureType()
    {
        // Constructor
    }

    public ALiteralFeatureType(
        @SuppressWarnings("hiding") PEnumerationLiteralDecl _enumerationLiteralDecl_)
    {
        // Constructor
        setEnumerationLiteralDecl(_enumerationLiteralDecl_);

    }

    @Override
    public Object clone()
    {
        return new ALiteralFeatureType(
            cloneNode(this._enumerationLiteralDecl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALiteralFeatureType(this);
    }

    public PEnumerationLiteralDecl getEnumerationLiteralDecl()
    {
        return this._enumerationLiteralDecl_;
    }

    public void setEnumerationLiteralDecl(PEnumerationLiteralDecl node)
    {
        if(this._enumerationLiteralDecl_ != null)
        {
            this._enumerationLiteralDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enumerationLiteralDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enumerationLiteralDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enumerationLiteralDecl_ == child)
        {
            this._enumerationLiteralDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enumerationLiteralDecl_ == oldChild)
        {
            setEnumerationLiteralDecl((PEnumerationLiteralDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
