/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ANavigableAssociationModifier extends PAssociationModifier
{
    private TNot _not_;
    private TNavigable _navigable_;

    public ANavigableAssociationModifier()
    {
        // Constructor
    }

    public ANavigableAssociationModifier(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") TNavigable _navigable_)
    {
        // Constructor
        setNot(_not_);

        setNavigable(_navigable_);

    }

    @Override
    public Object clone()
    {
        return new ANavigableAssociationModifier(
            cloneNode(this._not_),
            cloneNode(this._navigable_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANavigableAssociationModifier(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public TNavigable getNavigable()
    {
        return this._navigable_;
    }

    public void setNavigable(TNavigable node)
    {
        if(this._navigable_ != null)
        {
            this._navigable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._navigable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._navigable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._navigable_ == child)
        {
            this._navigable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._navigable_ == oldChild)
        {
            setNavigable((TNavigable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
