/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ANotNullUnaryOpLevel0 extends PUnaryOpLevel0
{
    private TQuestion _question_;

    public ANotNullUnaryOpLevel0()
    {
        // Constructor
    }

    public ANotNullUnaryOpLevel0(
        @SuppressWarnings("hiding") TQuestion _question_)
    {
        // Constructor
        setQuestion(_question_);

    }

    @Override
    public Object clone()
    {
        return new ANotNullUnaryOpLevel0(
            cloneNode(this._question_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotNullUnaryOpLevel0(this);
    }

    public TQuestion getQuestion()
    {
        return this._question_;
    }

    public void setQuestion(TQuestion node)
    {
        if(this._question_ != null)
        {
            this._question_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._question_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._question_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._question_ == child)
        {
            this._question_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._question_ == oldChild)
        {
            setQuestion((TQuestion) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
