/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ANotUnaryOperator extends PUnaryOperator
{
    private TNot _not_;

    public ANotUnaryOperator()
    {
        // Constructor
    }

    public ANotUnaryOperator(
        @SuppressWarnings("hiding") TNot _not_)
    {
        // Constructor
        setNot(_not_);

    }

    @Override
    public Object clone()
    {
        return new ANotUnaryOperator(
            cloneNode(this._not_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotUnaryOperator(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
