/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ARoleClassModifier extends PClassModifier
{
    private TRole _role_;

    public ARoleClassModifier()
    {
        // Constructor
    }

    public ARoleClassModifier(
        @SuppressWarnings("hiding") TRole _role_)
    {
        // Constructor
        setRole(_role_);

    }

    @Override
    public Object clone()
    {
        return new ARoleClassModifier(
            cloneNode(this._role_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARoleClassModifier(this);
    }

    public TRole getRole()
    {
        return this._role_;
    }

    public void setRole(TRole node)
    {
        if(this._role_ != null)
        {
            this._role_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._role_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._role_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._role_ == child)
        {
            this._role_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._role_ == oldChild)
        {
            setRole((TRole) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
