/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ASubnamespaceTopLevelElementChoice extends PTopLevelElementChoice
{
    private PSubNamespace _subNamespace_;

    public ASubnamespaceTopLevelElementChoice()
    {
        // Constructor
    }

    public ASubnamespaceTopLevelElementChoice(
        @SuppressWarnings("hiding") PSubNamespace _subNamespace_)
    {
        // Constructor
        setSubNamespace(_subNamespace_);

    }

    @Override
    public Object clone()
    {
        return new ASubnamespaceTopLevelElementChoice(
            cloneNode(this._subNamespace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubnamespaceTopLevelElementChoice(this);
    }

    public PSubNamespace getSubNamespace()
    {
        return this._subNamespace_;
    }

    public void setSubNamespace(PSubNamespace node)
    {
        if(this._subNamespace_ != null)
        {
            this._subNamespace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subNamespace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subNamespace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subNamespace_ == child)
        {
            this._subNamespace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subNamespace_ == oldChild)
        {
            setSubNamespace((PSubNamespace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
