/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ATransitionTriggerTail extends PTransitionTriggerTail
{
    private TComma _comma_;
    private PTransitionTrigger _transitionTrigger_;
    private PTransitionTriggerTail _transitionTriggerTail_;

    public ATransitionTriggerTail()
    {
        // Constructor
    }

    public ATransitionTriggerTail(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PTransitionTrigger _transitionTrigger_,
        @SuppressWarnings("hiding") PTransitionTriggerTail _transitionTriggerTail_)
    {
        // Constructor
        setComma(_comma_);

        setTransitionTrigger(_transitionTrigger_);

        setTransitionTriggerTail(_transitionTriggerTail_);

    }

    @Override
    public Object clone()
    {
        return new ATransitionTriggerTail(
            cloneNode(this._comma_),
            cloneNode(this._transitionTrigger_),
            cloneNode(this._transitionTriggerTail_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATransitionTriggerTail(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PTransitionTrigger getTransitionTrigger()
    {
        return this._transitionTrigger_;
    }

    public void setTransitionTrigger(PTransitionTrigger node)
    {
        if(this._transitionTrigger_ != null)
        {
            this._transitionTrigger_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._transitionTrigger_ = node;
    }

    public PTransitionTriggerTail getTransitionTriggerTail()
    {
        return this._transitionTriggerTail_;
    }

    public void setTransitionTriggerTail(PTransitionTriggerTail node)
    {
        if(this._transitionTriggerTail_ != null)
        {
            this._transitionTriggerTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._transitionTriggerTail_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._transitionTrigger_)
            + toString(this._transitionTriggerTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._transitionTrigger_ == child)
        {
            this._transitionTrigger_ = null;
            return;
        }

        if(this._transitionTriggerTail_ == child)
        {
            this._transitionTriggerTail_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._transitionTrigger_ == oldChild)
        {
            setTransitionTrigger((PTransitionTrigger) newChild);
            return;
        }

        if(this._transitionTriggerTail_ == oldChild)
        {
            setTransitionTriggerTail((PTransitionTriggerTail) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
