/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TActor extends Token
{
    public TActor()
    {
        super.setText("actor");
    }

    public TActor(int line, int pos)
    {
        super.setText("actor");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TActor(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTActor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TActor text.");
    }
}
