/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TAny extends Token
{
    public TAny()
    {
        super.setText("any");
    }

    public TAny(int line, int pos)
    {
        super.setText("any");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAny(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAny(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAny text.");
    }
}
