/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TComposition extends Token
{
    public TComposition()
    {
        super.setText("composition");
    }

    public TComposition(int line, int pos)
    {
        super.setText("composition");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComposition(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComposition(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComposition text.");
    }
}
