/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TExtent extends Token
{
    public TExtent()
    {
        super.setText("extent");
    }

    public TExtent(int line, int pos)
    {
        super.setText("extent");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TExtent(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExtent(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TExtent text.");
    }
}
