/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TParameterset extends Token
{
    public TParameterset()
    {
        super.setText("parameterset");
    }

    public TParameterset(int line, int pos)
    {
        super.setText("parameterset");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TParameterset(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTParameterset(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TParameterset text.");
    }
}
