/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TPermission extends Token
{
    public TPermission()
    {
        super.setText("permission");
    }

    public TPermission(int line, int pos)
    {
        super.setText("permission");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPermission(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPermission(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPermission text.");
    }
}
