/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TRead extends Token
{
    public TRead()
    {
        super.setText("read");
    }

    public TRead(int line, int pos)
    {
        super.setText("read");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRead(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRead(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRead text.");
    }
}
