/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TReadonly extends Token
{
    public TReadonly()
    {
        super.setText("readonly");
    }

    public TReadonly(int line, int pos)
    {
        super.setText("readonly");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReadonly(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReadonly(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReadonly text.");
    }
}
