/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TSubsets extends Token
{
    public TSubsets()
    {
        super.setText("subsets");
    }

    public TSubsets(int line, int pos)
    {
        super.setText("subsets");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSubsets(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSubsets(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSubsets text.");
    }
}
