/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TTerminate extends Token
{
    public TTerminate()
    {
        super.setText("terminate");
    }

    public TTerminate(int line, int pos)
    {
        super.setText("terminate");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTerminate(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTerminate(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTerminate text.");
    }
}
