/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstratt.mdd.frontend.textuml.grammar.node;

import com.abstratt.mdd.frontend.textuml.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TUnlink extends Token
{
    public TUnlink()
    {
        super.setText("unlink");
    }

    public TUnlink(int line, int pos)
    {
        super.setText("unlink");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUnlink(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUnlink(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUnlink text.");
    }
}
