# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        echo "<settings><servers><server><id>github</id><username>abstratt</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > tmp-deploy-settings.xml
        mvn -X -B package --settings tmp-deploy-settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.RELENG_GITHUB_TOKEN }}        
